[programs.localnet]
alaatoken = "7vHLYGEkX8TnsqRW1bKLUAFPpwazpebBRNAF1AKdKkQm"

[programs.devnet]
alaatoken = "7vHLYGEkX8TnsqRW1bKLUAFPpwazpebBRNAF1AKdKkQm"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/alaa/.config/solana/id.json"

[scripts]
test = "yarn vitest"
initialize = "yarn cli initialize"
reset = "yarn cli reset"
mint = "yarn cli mint"
