[programs.localnet]
alaatoken = "DgaUVK7Mz1ExQEH2g25i1GRt8xwhh13v9UU5y2ncGXit"
registrar = "BFq6fMJ4DuGriFeQs2uBPcYEzntU6NwVitD3LhujhRtv"

[programs.devnet]
alaatoken = "DgaUVK7Mz1ExQEH2g25i1GRt8xwhh13v9UU5y2ncGXit"
registrar = "BFq6fMJ4DuGriFeQs2uBPcYEzntU6NwVitD3LhujhRtv"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/alaa/.config/solana/id.json"

[scripts]
test = "yarn vitest"
setup = "yarn cli setup"
reset = "yarn cli reset"
mint = "yarn cli mint"
address = "cat token.md"
