[package]
name = "idl-generator"
version = "0.1.0"
edition = "2021"
authors = ["Alaa Zorkane <alaazorkane@gmail.com>"]
license = "MIT"

[dependencies]
clap = { version = "3.0.10", features = ["derive"] }
paris = "1.5.9"
walkdir = "2.3.2"
